spring.application.name=shopSphere
<<<<<<< HEAD
server.port=9091

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
=======
server.port=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
>>>>>>> b376d2849d68b5b605319a20e8fbb0c204e5465d

# Example URL, make sure to keep your actual database name
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?options=-c%20timezone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=ayush
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=
info.app.version=
info.app.description=




