spring.application.name=shopSphere
server.port=9090

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=ShopSphere
info.app.version=1.0.0
info.app.description=Spring Boot E-commerce Project




